### ISSUE TITLE
(little) Bug Report: Dark Mode Text Color Issue in Filament Tree View Plugin

### ISSUE THREAD

**Issue by ArneM-immalle** [cube-agency/filament-tree-view#4]
When using the Filament Tree View plugin in dark mode, there is an issue with text visibility. The text color remains white, making it difficult to read against the white background. Additionally, the branch icons also remain white, resulting in poor contrast.

![afbeelding](https://github.com/cube-agency/filament-tree-view/assets/43138132/d273a906-e19a-4754-80f6-5b41db7c73c8)

**Comment by ArneM-immalle** [comment]
Hi, do you know when you think this will be implemented? @cliche23 @dmitrijsmihailovs  :)

**Comment by miks** [comment]
@ArneM-immalle pull request, anyone?

**Comment by cliche23** [comment]
@ArneM-immalle in progress.

**Comment by cliche23** [comment]
https://github.com/cube-agency/filament-tree-view/releases/tag/v1.0.5
